### PR TITLE
Enable logging

### PR DESCRIPTION
**Pull request by NRHelmi**
This PR enables logging in the SDK using `Serilog` ~~framework~~ library and `log.debug` useful response information including `X-Request-ID` header and `transaction id`

### CODE REVIEW

**Comment by larf311** [comment]
I don't think we need a logging framework here. SDKs should have minimal dependencies. A good set of design principles can be found here: https://develop.sentry.dev/sdk/philosophy/

**Comment by NRHelmi** [comment]
> I don't think we need a logging framework here. SDKs should have minimal dependencies. A good set of design principles can be found here: https://develop.sentry.dev/sdk/philosophy/

dotnet core has no builtin logging API and I don't think we need to have a logger implementation in the sdk, that's why I started by checking couples of c# sdks like the aws sdk and they seem to be using `log4net`, `Microsoft logging extension`, `serilog` and couple of others frameworks and libraries. I tried to avoid as much to integrate logging frameworks since they are more complex to integrate, to configure and to use if compared to libraries. `serilog` is a library (it's not a framework as I mentioned in the PR description) and it is to light and easy to setup. So after all, our options are either to integrate a lightweight logging library like `serilog` which I find it more convenient or to have our own logging implementation (to avoid I believe we don't need to reinvent the wheel).

**Comment by larf311** [comment]
I looked at some other SDKs as well (auth0, launchdarkly, azure) and from what I can tell they don't have dependencies. I know Brad has mentioned no dependencies before as well. Since we're literally just adding a few print statements in this PR I think we should do that as simply as possible for now. Adding a dependency should be a big deal with a very critical need.

**Comment by NRHelmi** [comment]
@larf311  I still think integrating a logging library is more convenient. Anyway in the v1 sdks we used to have a config to enable/disable debugging messages, this should be an option maybe also an environment variable, what do you suggest as an alternative to a logging library ?

**Review by miazamrai — COMMENTED** [review]
Since all the logs are currently going to the console anyways, so print statements are fine. One thing we can do is that write our own logging class with a static function to log to console, which we can enhance later on with configuration. when needed.

**Pull request closed without merging**
