### PR TITLE
Code style improvements

### PR DESCRIPTION
**Pull request by Zlata-Zueva**
* Adjusts StyleCop configuration to better match C# coding conventions and follows code style accordingly.
* Adds enums for `EngineState`, `DatabaseState`, `TransactionAsyncState`, `TransactionMode` with useful methods and updates the model to return them instead of strings.
* Created solution folders structure.
* Simplifies code using such language capabilities as *null propagation*, *string interpolation*, LINQ, etc.
* Fixes *possible NullReference* warnings.

### CODE REVIEW

**Review by stanislav-bedunkevich — APPROVED** [review]

**Comment by larf311** [comment]
@bradlo What do you think about the enums? I argued for having them a long time ago but others were [against them](https://relationalai.slack.com/archives/C01G7FKCX6F/p1621620068071600). The idea is that if we introduce a new engine size, we wouldn't have to release a new SDK (and users have to upgrade) to take advantage of it. Perhaps engine size is different than states though.

**Comment by larf311** [comment]
I really appreciate the PR, but in the future, could submit each of the bullets as separate PRs, especially StyleCop changes? PRs with 116 file changes are effectively impossible to review.

**Comment by stanislav-bedunkevich** [comment]
> against them

@larf311 @bradlo on the other hand, having enums for that feels more natural, as we can document each item, possibly with some more details if needed (like what's the cpu/mem power, cost etc).

In addition, if we're talking about backward compatibility, we would need to be able to support XS-XL sizes in the backend anyway if we decide to rename them etc, right? If talking about additions, it should be fine to update some of the major versions of the SDK we support (and which are in use) with a patch adding more engines. The users will have to update their code anyway?

**Comment by stanislav-bedunkevich** [comment]
> I really appreciate the PR, but in the future, could you submit each of the bullets as separate PRs, _especially_ StyleCop changes? PRs with 116 file changes are effectively impossible to review.

It makes perfect sense, apologies for having this this big, as the amount of stylecop changes got rather huge.

**Comment by bradlo** [comment]
enums are language dependent, in most modern languages, enums are the right thing to do. however, i added them to the python SDK based on feedback, and regret it because it just makes the code more awkward given the need to explicitly convert in too many cases. i think the C# deltas in the PR look great.

**Pull request merged**
