### PR TITLE
Optimize exec async response

### PR DESCRIPTION
**Pull request by NRHelmi**
Return fast path response if exists

### CODE REVIEW

**Review by larf311 — COMMENTED** [review]
Seems like we should add a test for this, no?

**Comment by NRHelmi** [comment]
> Seems like we should add a test for this, no?

@larf311 sadly we won't in this PR, we need to have a separate PR for setting up unit tests and mocking somehow this behavior :pray:

**Comment by larf311** [comment]
Oh no, we don't have any tests 😬 ?

**Review by larf311 — APPROVED** [review]

**Comment by NRHelmi** [comment]
> Oh no, we don't have any tests grimacing ?

Only integration tests currently :pray:

**Pull request merged**
